### ISSUE TITLE
Discrepancy in dist_rq_rf versus (rq_dist_km / rf_dist_km)

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#779]
*Not related to the school's data; it's about commute data.*

Looking at both national and Cambridge route data, there seems to be a bit of difference between `dist_rq_rf` and `rq_dist_km / rf_dist_km`. Here is an example from Cambridge. 

![Screenshot_2019-08-01 Propensity to Cycle Tool - Cambridgeshire(1)](https://user-images.githubusercontent.com/10958628/62283892-741abe00-b44a-11e9-91bc-374599eef1c7.png)

Fast Route Distance: `5 km`

![Screenshot_2019-08-01 Propensity to Cycle Tool - Cambridgeshire](https://user-images.githubusercontent.com/10958628/62283889-7250fa80-b44a-11e9-9a4e-51e4be3d9c21.png)

Quite Route Distance: `5.1 km`

This makes `dist_rq_rf` = `5.1 / 5` = `1.02` and `rqincr` (the value you see in the popup) to be: `round((100 * 1.02) - 100, 1)` = `2%`. However when you look at `Distance compared w. fastest route (%)`, it is shown as `3.2%` which is not right.

Looking at the summary data for `Cambridge`, please see the difference between the two:

```
Browse[1]> summary(data@data$rq_dist_km / data@data$rf_dist_km)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.7016  0.9149  1.0350  1.0219  1.1269  1.4067 
Browse[1]> summary(data@data$dist_rq_rf)
    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.8076  0.9862  1.0000  1.0005  1.0143  1.1741 
```

Similarly the national data (downloaded from the app on the test-server), is quite different for the two as well. See the summary here:

```
summary(rd@data$rq_dist_km / rd@data$rf_dist_km)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.2027  1.0098  1.0664  1.0849  1.1397  5.4436
summary(rd@data$dist_rq_rf)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.2599  1.0131  1.0602  1.0799  1.1248  2.6658 
```

Any ideas what's going on here?

**Comment by AnnaGoodman1** [comment]
hi there @usr110 , oh good spot / ugh.

I have looked and you are right, it is discrepant. The reason is
1) the rf_dist_km value '5' shown there (really 5.047km unrounded) is actually the average distance travelled by the commuters living there based on their LSOA OD distances.  This is slightly different to the distance between the MSOA OD centroids, which is 4.922km
2) the dist_rq_rf and rq_dist_km values, by contrast, are based on the actual MSOA OD data and distances.

I guess I should switch it to have the MSOA OD distance there. The v minor advantage of the LSOA average is it relates more closely to the scenario estimated numbers of cyclists (which are built up from the LSOA data), but I think this is much more than outweighed by the confusingness of what you have found. If I had noticed this before I would have fixed this...

One good thing is this will only have been incorrect for a couple of months, since it dates from when we introduce the nearmarket scenario

@Robinlovelace, sorry, a reason to delay deployment?

**Comment by usr110** [comment]
Thanks @AnnaGoodman1 for such a detailed response. This clears up the confusion.

 >I guess I should switch it to have the MSOA OD distance there.

I think so too.

**Comment by Robinlovelace** [comment]
> @Robinlovelace, sorry, a reason to delay deployment?

I don't think so. One thing at a time and I don't think we need to announce this change. 

Great find @usr110 and thanks for quickfire response @AnnaGoodman1. To clarify, which repos will need updating to fix this? I imagine if it only includes changes to the data it could include the data repos and `pct-scripts`.

**Comment by AnnaGoodman1** [comment]
yes, only affect the data, and new data should be ready by end of weekend. so if we don't deplot today could do a single deployment to live start next week. Or do 2 deployments, I don't very much mind. and yes, data repos + pct-scripts will change, only the sha pointing to data will change in pct-shiny

**Comment by AnnaGoodman1** [comment]
![image](https://user-images.githubusercontent.com/11818225/62359432-ad1c6680-b50e-11e9-95d5-08afd03a5475.png)
this is now fixed locally on my laptop, am pushing data to git now

**Comment by usr110** [comment]
Great, thanks a bunch @AnnaGoodman1 

Look forward to see the changes on the server.

**Comment by usr110** [comment]
@AnnaGoodman1 for some reason the data hasn't been updated, it seems, on the test-server.

Would the server need restarting @nikolai-b ? I am still seeing the old values reported in the first message of the thread.

**Comment by AnnaGoodman1** [comment]
sorry @usr110 , I think my mistake mistyping sha: see https://github.com/npct/pct-shiny/pull/784

**Comment by usr110** [comment]
> 
> 
> sorry @usr110 , I think my mistake mistyping sha: see #784

Working now. Thanks!
