### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#879]
On region sites e.g. https://www.pct.bike/m/?r=west-yorkshire

With this message:

```
The application exited during initialization.
```
![image](https://user-images.githubusercontent.com/1825120/144470745-b8e07897-45c5-4014-81fa-3136792ca1bd.png)

**Comment by nikolai-b** [comment]
Only for (npt2) Cambridge servers.  Mythic Beasts asked if they could upgrade our version of Debian as it was unsupported.  We did npct0 without an issue but they had problems with npt2.

**Comment by Robinlovelace** [comment]
First reported at 16:48 today. I notice there were a couple of [commits yesterday](https://github.com/npct/pct-shiny/commits/master) that may have coincided with these errors.

**Comment by Robinlovelace** [comment]
I'm not getting a response form npt1: http://npt1.vs.mythic-beasts.com/m/?r=north-east

In any case the user facing site is down, is there a way to not point traffic to the server that is down. Sounds like you're on the case @nikolai-b, thanks for the quick response!

**Comment by nikolai-b** [comment]
Fixed, I'll update the server instructions, needed to reinstall the `digest` package.

We don't let you point directly to a server as haproxy uses cookies.

We have `cam_` and `hex_`:

![Screenshot from 2021-12-02 17-32-45](https://user-images.githubusercontent.com/6289830/144473476-84ea49ae-13c2-4b8b-a018-c85c48998c00.png)

**Comment by Robinlovelace** [comment]
I'm still seeing the error message https://www.pct.bike/m/?r=north-east

**Comment by Robinlovelace** [comment]
Imagine it's just a case of rebooting the server that was down but suggest we close this after it has been tested as working.

**Comment by Robinlovelace** [comment]
Demo from a new private tab:

![Peek 2021-12-02 17-37](https://user-images.githubusercontent.com/1825120/144474392-381fbe10-3cf4-4682-b687-8fc7ae32e2fc.gif)

**Comment by Robinlovelace** [comment]
Happy to say, it's back up for me so closing :tada: 

https://www.pct.bike/m/?r=west-yorkshire

Great work Nikolai

**Comment by JDWoodcock** [comment]
thanks Nikolai
